import { CardType } from '../types/game';

// Sample black cards (questions/fill-in-the-blank statements)
export const blackCards: CardType[] = [
  { id: 'b1', text: "Why can't I sleep at night?" },
  { id: 'b2', text: "What's that smell?" },
  { id: 'b3', text: "I got 99 problems but _____ ain't one." },
  { id: 'b4', text: "What's the next Happy Meal toy?" },
  { id: 'b5', text: "What's my secret power?" },
  { id: 'b6', text: "What ended my last relationship?" },
  { id: 'b7', text: "What's that sound?" },
  { id: 'b8', text: "What will always get you laid?" },
  { id: 'b9', text: "What would grandma find disturbing, yet oddly charming?" },
  { id: 'b10', text: "What did I bring back from Mexico?" },
  { id: 'b11', text: "What don't you want to find in your Chinese food?" },
  { id: 'b12', text: "_____ + _____ = _____" },
  { id: 'b13', text: "What will I bring back in time to convince people I am a powerful wizard?" },
  { id: 'b14', text: "How am I maintaining my relationship status?" },
  { id: 'b15', text: "What gives me uncontrollable gas?" },
  { id: 'b16', text: "What do old people smell like?" },
  { id: 'b17', text: "The class field trip was completely ruined by _____." },
  { id: 'b18', text: "When I'm a billionaire, I'll erect a 50-foot statue to commemorate _____." },
  { id: 'b19', text: "What's my anti-drug?" },
  { id: 'b20', text: "What never fails to liven up the party?" },
];

// Sample white cards (answers)
export const whiteCards: CardType[] = [
  { id: 'w1', text: "Flying spaghetti monster." },
  { id: 'w2', text: "Not wearing pants." },
  { id: 'w3', text: "A disappointed optimist." },
  { id: 'w4', text: "A lifetime of sadness." },
  { id: 'w5', text: "A tiny horse." },
  { id: 'w6', text: "Being on fire." },
  { id: 'w7', text: "Bees?" },
  { id: 'w8', text: "Cards Against Humanity." },
  { id: 'w9', text: "Fancy Feast." },
  { id: 'w10', text: "Figuring out how to have a time." },
  { id: 'w11', text: "Flavor-blasted Goldfish." },
  { id: 'w12', text: "Grandma." },
  { id: 'w13', text: "Insufficient funds." },
  { id: 'w14', text: "Keanu Reeves." },
  { id: 'w15', text: "Kids with terminal illnesses." },
  { id: 'w16', text: "Mistaking a raccoon for a cat." },
  { id: 'w17', text: "Pretending to care." },
  { id: 'w18', text: "Preteens." },
  { id: 'w19', text: "Puppies!" },
  { id: 'w20', text: "Science." },
  { id: 'w21', text: "Nicolas Cage." },
  { id: 'w22', text: "A really cool hat." },
  { id: 'w23', text: "A falcon with a cap on its head." },
  { id: 'w24', text: "Being fabulous." },
  { id: 'w25', text: "Growing a pair." },
  { id: 'w26', text: "Judge Judy." },
  { id: 'w27', text: "The inevitable heat death of the universe." },
  { id: 'w28', text: "The folly of man." },
  { id: 'w29', text: "Exactly what you'd expect." },
  { id: 'w30', text: "The American Dream." },
  { id: 'w31', text: "Sweet, sweet vengeance." },
  { id: 'w32', text: "The Rapture." },
  { id: 'w33', text: "My inner demons." },
  { id: 'w34', text: "A hot mess." },
  { id: 'w35', text: "Explosions." },
  { id: 'w36', text: "That thing that electrocutes your abs." },
  { id: 'w37', text: "Telling a shaggy dog story." },
  { id: 'w38', text: "Poor life choices." },
  { id: 'w39', text: "My collection of high-tech sex toys." },
  { id: 'w40', text: "The true meaning of Christmas." },
];